# Pandas

In [3]:
import pandas as pd

In [17]:
info = {
    "Name" : ["pankaj" ,"maurya" , "utsah" , "kumar"],
    "cgpa" : [2.3 ,4.5,8.9,9.3]
}

df = pd.DataFrame(info)
print(df)

     Name  cgpa
0  pankaj   2.3
1  maurya   4.5
2   utsah   8.9
3   kumar   9.3

In [15]:
df

     Name  cgpa
0  pankaj   2.3
1  maurya   4.5
2   utsah   8.9
3   kumar   9.3

# series in Pandas

In [18]:
import pandas as pd

In [37]:
a = pd.Series([1,2,3,4,5,6,7])
print(a)
print(type(a))
print(a[2])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
<class 'pandas.core.series.Series'>
3

In [45]:
s = pd.Series([12,32,34,67] , index =["pankaj" ,"aman" , "kasis", "rajan"])

print(s)
print(s["pankaj"])
print(s["aman"])
print(s.index)

pankaj    12
aman      32
kasis     34
rajan     67
dtype: int64
12
32
Index(['pankaj', 'aman', 'kasis', 'rajan'], dtype='object')

# properties of series

In [46]:
import pandas as pd

In [47]:
# Homogenous

s = pd.Series([1,2,3,4,5,"abj"])
print(s)

0      1
1      2
2      3
3      4
4      5
5    abj
dtype: object

In [50]:
# vectorized operation

s1 = pd.Series([1,2,3,5,6])
s2 = pd.Series([12,23,54,23])

print(s1+s2)

0    13.0
1    25.0
2    57.0
3    28.0
4     NaN
dtype: float64

In [54]:
s1 = pd.Series([1,2,3,5,6])
s2 = pd.Series([12,23,54,23])

# print(s1)
# s1[0] = 100
# print(s1)

new_s1 = s1.drop(0)
print(s1)
print(new_s1)

0    1
1    2
2    3
3    5
4    6
dtype: int64
1    2
2    3
3    5
4    6
dtype: int64

# DataFrame

In [55]:
import pandas as pd

In [62]:
# from distrinary
info = {
    "Name" : ["adam","bob","charli","alexa"],
    "age" : [40,23,12,23],
    "gpa" : [2.4,5.7,9.7,6.9]
}
# print(info["Name"])
# print(info)

df = pd.DataFrame(info)


print(df)

     Name  age  gpa
0    adam   40  2.4
1     bob   23  5.7
2  charli   12  9.7
3   alexa   23  6.9

In [68]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'age', 'gpa'], dtype='object')

In [72]:
# from list to list

lst = pd.DataFrame([[12 , "pankaj"],[32 , "maurya"], [45 , "rajan"]] , columns = ["roll","name"])
print(lst)

   roll    name
0    12  pankaj
1    32  maurya
2    45   rajan

In [75]:
# from numpy array list

import numpy as np

arr = np.array([[1,2,3] , [4,5,6]])
print(arr)

df = pd.DataFrame(arr , columns = ["a" , "b" , "c"])
print(df)

[[1 2 3]
 [4 5 6]]
   a  b  c
0  1  2  3
1  4  5  6

In [76]:
df

   a  b  c
0  1  2  3
1  4  5  6